set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(DEFINED ENV{OSXCROSS_BIN})
	set(OSXCROSS_BIN "$ENV{OSXCROSS_BIN}")
elseif(EXISTS "/home/illia/proj/third-party/osxcross/target/bin/o64-clang")
	set(OSXCROSS_BIN "/home/illia/proj/third-party/osxcross/target/bin")
endif()

set(_macos_arch "")
if(DEFINED CMAKE_OSX_ARCHITECTURES)
	set(_macos_arch "${CMAKE_OSX_ARCHITECTURES}")
endif()

if(OSXCROSS_BIN)
	if(_macos_arch MATCHES "arm64" AND NOT _macos_arch MATCHES "x86_64")
		if(EXISTS "${OSXCROSS_BIN}/oa64-clang")
			set(CMAKE_C_COMPILER "${OSXCROSS_BIN}/oa64-clang")
			set(CMAKE_CXX_COMPILER "${OSXCROSS_BIN}/oa64-clang++")
			set(CMAKE_OBJC_COMPILER "${OSXCROSS_BIN}/oa64-clang")
		elseif(EXISTS "${OSXCROSS_BIN}/arm64-apple-darwin25.1-clang")
			set(CMAKE_C_COMPILER "${OSXCROSS_BIN}/arm64-apple-darwin25.1-clang")
			set(CMAKE_CXX_COMPILER "${OSXCROSS_BIN}/arm64-apple-darwin25.1-clang++")
			set(CMAKE_OBJC_COMPILER "${OSXCROSS_BIN}/arm64-apple-darwin25.1-clang")
		endif()
		if(EXISTS "${OSXCROSS_BIN}/arm64-apple-darwin25.1-ar")
			set(CMAKE_AR "${OSXCROSS_BIN}/arm64-apple-darwin25.1-ar")
			set(CMAKE_RANLIB "${OSXCROSS_BIN}/arm64-apple-darwin25.1-ranlib")
			set(CMAKE_NM "${OSXCROSS_BIN}/arm64-apple-darwin25.1-nm")
			set(CMAKE_STRIP "${OSXCROSS_BIN}/arm64-apple-darwin25.1-strip")
		endif()
	else()
		set(CMAKE_C_COMPILER "${OSXCROSS_BIN}/o64-clang")
		set(CMAKE_CXX_COMPILER "${OSXCROSS_BIN}/o64-clang++")
		set(CMAKE_OBJC_COMPILER "${OSXCROSS_BIN}/o64-clang")
		if(EXISTS "${OSXCROSS_BIN}/x86_64-apple-darwin25.1-ar")
			set(CMAKE_AR "${OSXCROSS_BIN}/x86_64-apple-darwin25.1-ar")
			set(CMAKE_RANLIB "${OSXCROSS_BIN}/x86_64-apple-darwin25.1-ranlib")
			set(CMAKE_NM "${OSXCROSS_BIN}/x86_64-apple-darwin25.1-nm")
			set(CMAKE_STRIP "${OSXCROSS_BIN}/x86_64-apple-darwin25.1-strip")
		endif()
	endif()
else()
	set(CMAKE_C_COMPILER o64-clang)
	set(CMAKE_CXX_COMPILER o64-clang++)
	set(CMAKE_OBJC_COMPILER o64-clang)
endif()

if(NOT DEFINED CMAKE_OBJC_COMPILE_OBJECT)
	set(CMAKE_OBJC_COMPILE_OBJECT "<CMAKE_OBJC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
endif()
if(NOT DEFINED CMAKE_INCLUDE_FLAG_OBJC)
	set(CMAKE_INCLUDE_FLAG_OBJC "-I")
endif()

set(CMAKE_OSX_DEPLOYMENT_TARGET 10.15)

set(CMAKE_CROSSCOMPILING TRUE)
